version: "3"

services:
  frontend:
    ports:
      - 3000:3000
    volumes:
      - ./react:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]

  api-gateway:
    # Change node env.
    # environment:
    #   - NODE_ENV=development
    # Expose port for sending requests on local machine
    ports:
      - 8080:3000
    # Live file updates
    volumes:
      - ./gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]

  user-service:
    # Live file updates
    volumes:
      - ./user-service:/app
    environment:
      - FLASK_DEBUG=1

  user-db:
    # Expose port for DB viewing on local machine
    ports:
      - 5433:5432

  auth-service:
    # Live file updates
    volumes:
      - ./auth-service:/app
    environment:
      - FLASK_DEBUG=1

  auth-db:
    # Expose port for DB viewing on local machine
    ports:
      - 5432:5432

  note-service:
    # Live file updates
    volumes:
      - ./note-service:/app
    environment:
      - FLASK_DEBUG=1

  note-db:
    # Expose port for DB viewing on local machine
    ports:
      - 5434:5432
