version: "3"

# FOR END TO END TESTING W/ GATEWAY. RUN MICROSERVICES USING TEST DBs, RUN GATEWAY TESTS

services:
  api-gateway:
    # Change node env.
    environment:
      - NODE_ENV=test
    # Run jest
    command: ["npm", "run", "test"]

  user-service:
    # Run service as normal for gateway requests, but with the test DB
    command: ["./wait-for", "test-user-db:5432", "--", "./start-script"]

  auth-service:
    # Run service as normal for gateway requests, but with the test DB
    command: ["./wait-for", "test-auth-db:5432", "--", "./start-script"]
