version: "3"

# COMMON CONFIG FOR ALL ENVIRONMENTS. EDIT .ENV TEMPLATES FOR ENVIRONMENT SPECIFIC CONFIG
# DON'T CHANGE

services:
  frontend:
    networks:
      - app-network
    depends_on:
      - api-gateway

  api-gateway:
    build: ./gateway
    networks:
      - app-network
    environment:
      - PORT=3000
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8080:3000

    depends_on:
      user-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      note-service:
        condition: service_healthy

  user-service:
    build: ./user-service
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgresql://user_service_user:${USER_DB_PASSWORD}@user-db/userdb
    depends_on:
      user-db:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgresql://auth_service_user:${AUTH_DB_PASSWORD}@auth-db/authdb
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      auth-db:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  note-service:
    build: ./note-service
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgresql://note_service_user:${NOTE_DB_PASSWORD}@note-db/notedb
    depends_on:
      note-db:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Databases
  user-db:
    image: postgres:alpine
    networks:
      - app-network
    volumes:
      - user-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=user_service_user
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD} # Defined in root .env, see template
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service_user -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-db:
    image: postgres:alpine
    networks:
      - app-network
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=auth_service_user
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD} # Defined in root .env, see template
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_service_user -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  note-db:
    image: postgres:alpine
    networks:
      - app-network
    volumes:
      - note-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notedb
      - POSTGRES_USER=note_service_user
      - POSTGRES_PASSWORD=${NOTE_DB_PASSWORD} # Defined in root .env, see template
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U note_service_user -d notedb"]
      interval: 10s
      timeout: 5s
      retries: 5

# Volumes & Network
volumes:
  user-db-data:
  auth-db-data:
  note-db-data:

networks:
  app-network:
    driver: bridge
