version: "3"

services:
  api-gateway:
    build: ./gateway
    networks:
      - backend
    environment:
      - PORT=3000
    depends_on:
      user-service:
        condition: service_healthy
      auth-service:
        condition: service_healthy

    command: ["npm", "run", "start"]

  user-service:
    build: ./user-service
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql://user_service_user:${USER_DB_PASSWORD}@user-db/userdb
    depends_on:
      user-db:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    command: ["./wait-for", "user-db:5432", "--", "./start-script"]

  user-db:
    image: postgres:alpine
    networks:
      - backend
    volumes:
      - user-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=user_service_user
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service_user -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    networks:
      - backend
    environment:
      - DATABASE_URL=postgresql://auth_service_user:${AUTH_DB_PASSWORD}@auth-db/authdb
      - SECRET_KEY=5RG1uLnB++zZBlSEmP0nSKYc92eiJm9sMcvPFZ4fHGw=
    depends_on:
      auth-db:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    command: ["./wait-for", "auth-db:5432", "--", "./start-script"]

  auth-db:
    image: postgres:alpine
    networks:
      - backend
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=authdb
      - POSTGRES_USER=auth_service_user
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_service_user -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  user-db-data:
  auth-db-data:

networks:
  backend:
    driver: bridge
