FROM node:alpine3.18 as build
WORKDIR /usr/src/app
COPY package*.json ./

RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine as prod
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80/tcp
CMD ["nginx", "-g", "daemon off;"]

