"""create tables

Revision ID: ac241ac164a4
Revises: 
Create Date: 2024-05-28 00:00:12.892623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac241ac164a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('billed', sa.Integer(), nullable=False),
    sa.Column('projectManager', sa.String(length=25), nullable=False),
    sa.Column('projectType', sa.Enum('SOC_1_TYPE_1', 'SOC_1_TYPE_2', 'SOC_2_TYPE_1', 'SOC_2_TYPE_2', 'OTHER', name='projecttype'), nullable=False),
    sa.Column('checkboxHeaders', sa.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sectionNumber', sa.Integer(), nullable=False),
    sa.Column('projectID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectID'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flagMarker', sa.Boolean(), nullable=False),
    sa.Column('controlNumber', sa.String(length=5), nullable=True),
    sa.Column('checkBoxes', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sectionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sectionID'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('controlOwner', sa.String(length=25), nullable=True),
    sa.Column('lastContactDate', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lineItemID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lineItemID'], ['line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_items')
    op.drop_table('line_items')
    op.drop_table('sections')
    op.drop_table('projects')
    # ### end Alembic commands ###
