"""create tables

Revision ID: cdb257509f11
Revises: 
Create Date: 2024-06-30 01:10:52.394252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb257509f11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('billed', sa.Float(), nullable=False),
    sa.Column('project_manager', sa.String(length=50), nullable=False),
    sa.Column('project_type', sa.String(length=15), nullable=False),
    sa.Column('checkbox_headers', sa.ARRAY(sa.String(length=15)), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("length(project_manager) >= 2 AND length(project_manager) <= 50 AND project_manager ~* '^[A-Za-z ]+$'", name='check_project_manager'),
    sa.CheckConstraint("length(project_type) >= 2 AND length(project_type) <= 15 AND project_type IN ('SOC 2 Type 1','Other','SOC 2 Type 2','SOC 1 Type 1','SOC 1 Type 2')", name='check_project_type'),
    sa.CheckConstraint("length(title) >= 2 AND length(title) <= 30 AND title ~* '^[A-Za-z0-9]+$'", name='check_title'),
    sa.CheckConstraint('0 <= billed AND billed <= 200', name='check_billed'),
    sa.CheckConstraint('0 <= budget AND budget <= 200', name='check_budget'),
    sa.CheckConstraint('array_length(checkbox_headers, 1) = 3', name='check_checkbox_headers'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sectionNumber', sa.Integer(), nullable=False),
    sa.Column('projectID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectID'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flagMarker', sa.Boolean(), nullable=False),
    sa.Column('controlNumber', sa.String(length=5), nullable=True),
    sa.Column('checkBoxes', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sectionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sectionID'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemName', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('controlOwner', sa.String(length=50), nullable=True),
    sa.Column('lastContactDate', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lineItemID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lineItemID'], ['line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_items')
    op.drop_table('line_items')
    op.drop_table('sections')
    op.drop_table('projects')
    # ### end Alembic commands ###
