"""create tables

Revision ID: f9a8b237f530
Revises: 
Create Date: 2024-06-30 04:42:46.988621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a8b237f530'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('billed', sa.Float(), nullable=False),
    sa.Column('project_manager', sa.String(length=50), nullable=False),
    sa.Column('project_type', sa.String(length=15), nullable=False),
    sa.Column('checkbox_headers', sa.ARRAY(sa.String(length=15)), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("length(project_manager) >= 2 AND length(project_manager) <= 50 AND project_manager ~* '^[A-Za-z ]+$'", name='check_project_manager'),
    sa.CheckConstraint("length(project_type) >= 2 AND length(project_type) <= 15 AND project_type IN ('SOC 2 Type 1','Other','SOC 2 Type 2','SOC 1 Type 2','SOC 1 Type 1')", name='check_project_type'),
    sa.CheckConstraint("length(title) >= 2 AND length(title) <= 30 AND title ~* '^[A-Za-z0-9]+$'", name='check_title'),
    sa.CheckConstraint('0 <= billed AND billed <= 200', name='check_billed'),
    sa.CheckConstraint('0 <= budget AND budget <= 200', name='check_budget'),
    sa.CheckConstraint('array_length(checkbox_headers, 1) = 3', name='check_checkbox_headers'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('section_number >= 1 AND section_number <= 99', name='check_section_number'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag_marker', sa.Boolean(), nullable=False),
    sa.Column('control_number', sa.String(length=5), nullable=True),
    sa.Column('check_boxes', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('array_length(check_boxes, 1) = 3', name='check_check_boxes_length'),
    sa.CheckConstraint('length(control_number) >= 4 AND length(control_number) <= 5', name='check_control_number_length'),
    sa.CheckConstraint('length(notes) >= 0 AND length(notes) <= 2000', name='check_notes_length'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('control_owner', sa.String(length=50), nullable=True),
    sa.Column('last_contact_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("length(control_owner) >= 2 AND length(control_owner) <= 50 AND control_owner ~* '^[A-Za-z ]+$'", name='check_control_owner'),
    sa.CheckConstraint("length(item_name) >= 2 AND length(item_name) <= 40 AND item_name ~* '^[A-Za-z0-9 ]+$'", name='check_item_name'),
    sa.CheckConstraint('length(description) >= 0 AND length(description) <= 200', name='check_description'),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_items')
    op.drop_table('line_items')
    op.drop_table('sections')
    op.drop_table('projects')
    # ### end Alembic commands ###
