version: "3"

services:
  frontend:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./react/src:/usr/src/app/src
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./react/default.conf:/etc/nginx/conf.d/default.conf:ro 
      # - /usr/src/app/node_modules
    # command: ["npm", "run", "build"]

  api-gateway:
    # Change node env.
    # environment:
    #   - NODE_ENV=development
    # Expose port for sending requests on local machine
    ports:
      - 8080:3000
    # Live file updates
    volumes:
      - ./gateway:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "start"]

  user-service:
    # Live file updates
    volumes:
      - ./user-service:/app
    environment:
      - FLASK_DEBUG=0

  user-db:
    # Expose port for DB viewing on local machine
    ports:
      - 5433:5432

  auth-service:
    # Live file updates
    volumes:
      - ./auth-service:/app
    environment:
      - FLASK_DEBUG=0

  auth-db:
    # Expose port for DB viewing on local machine
    ports:
      - 5432:5432

  note-service:
    # Live file updates
    volumes:
      - ./note-service:/app
    environment:
      - FLASK_DEBUG=0

  note-db:
    # Expose port for DB viewing on local machine
    ports:
      - 5434:5432
