version: "3"

services:
  api-gateway:
    # Change node env.
    environment:
      - NODE_ENV=test
    # Run jest
    command: ["npm", "run", "start"]

  user-service:
    # Use separate test database
    environment:
      - DATABASE_URL=postgresql://test_user_service_user:${USER_DB_PASSWORD}@test-user-db/testuserdb
    depends_on:
      test-user-db:
        condition: service_healthy
    command: ["./wait-for", "test-user-db:5432", "--", "./start-script-test"]

  # Test database for user service
  test-user-db:
    image: postgres:alpine
    networks:
      - app-network
    volumes:
      - test-user-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testuserdb
      - POSTGRES_USER=test_user_service_user
      - POSTGRES_PASSWORD=${USER_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user_service_user -d testuserdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5533:5432

  auth-service:
    # Use separate test database
    environment:
      - DATABASE_URL=postgresql://test_auth_service_user:${AUTH_DB_PASSWORD}@test-auth-db/testauthdb
    depends_on:
      test-auth-db:
        condition: service_healthy

    command: ["./wait-for", "test-auth-db:5432", "--", "./start-script-test"]

  # Test database for auth service
  test-auth-db:
    image: postgres:alpine
    networks:
      - app-network
    volumes:
      - test-auth-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testauthdb
      - POSTGRES_USER=test_auth_service_user
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_auth_service_user -d testauthdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5532:5432

  note-service:
    # Use separate test database
    environment:
      - DATABASE_URL=postgresql://test_note_service_user:${NOTE_DB_PASSWORD}@test-note-db/testnotedb
    depends_on:
      test-note-db:
        condition: service_healthy

    command: ["./wait-for", "test-note-db:5432", "--", "./start-script-test"]

  # Test database for auth service
  test-note-db:
    image: postgres:alpine
    networks:
      - app-network
    volumes:
      - test-note-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testnotedb
      - POSTGRES_USER=test_note_service_user
      - POSTGRES_PASSWORD=${NOTE_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_note_service_user -d testnotedb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5534:5432

volumes:
  test-user-db-data:
  test-auth-db-data:
  test-note-db-data:
