"""change custom number name

Revision ID: b473876bfdf2
Revises: d86890d993be
Create Date: 2024-04-17 21:11:25.572019

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b473876bfdf2"
down_revision = "d86890d993be"
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column(
        "project_sections", "section_number", new_column_name="custom_section_number"
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_sections", "custom_section_number", new_column_name="section_number"
    )

    # ### end Alembic commands ###
