"""remove non null constraint from custom types

Revision ID: bcfddd9617bc
Revises: b473876bfdf2
Create Date: 2024-04-17 22:39:29.946781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfddd9617bc'
down_revision = 'b473876bfdf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_sections', schema=None) as batch_op:
        batch_op.alter_column('custom_section_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('section_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_sections', schema=None) as batch_op:
        batch_op.alter_column('section_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('custom_section_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
