"""model validation

Revision ID: e1ec6f83d213
Revises: ee69fba3053c
Create Date: 2024-04-15 20:46:57.669321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ec6f83d213'
down_revision = 'ee69fba3053c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.alter_column('domain_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)

    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.alter_column('flag',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('item',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('project_section_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('project_sections', schema=None) as batch_op:
        batch_op.alter_column('section_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('section_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_project_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('project_types', schema=None) as batch_op:
        batch_op.alter_column('project_type',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)

    with op.batch_alter_table('section_types', schema=None) as batch_op:
        batch_op.alter_column('section_type',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('default_section_number',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.alter_column('user_project_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('user_project_issuance',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('user_project_budget',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_project_billed',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('project_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
        batch_op.alter_column('domain_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('domain_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('user_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('user_projects', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('project_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_project_billed',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_project_budget',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_project_issuance',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('user_project_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    with op.batch_alter_table('section_types', schema=None) as batch_op:
        batch_op.alter_column('default_section_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('section_type',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    with op.batch_alter_table('project_types', schema=None) as batch_op:
        batch_op.alter_column('project_type',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    with op.batch_alter_table('project_sections', schema=None) as batch_op:
        batch_op.alter_column('user_project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('section_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('section_number',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.alter_column('project_section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('item',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
        batch_op.alter_column('flag',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.alter_column('domain_name',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)

    # ### end Alembic commands ###
