"""create tables

Revision ID: ee69fba3053c
Revises: 
Create Date: 2024-04-14 20:49:17.882127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee69fba3053c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_type', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=60), nullable=True),
    sa.Column('default_section_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_project_name', sa.String(length=60), nullable=True),
    sa.Column('user_project_issuance', sa.Date(), nullable=True),
    sa.Column('user_project_budget', sa.Integer(), nullable=True),
    sa.Column('user_project_billed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('project_type_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_type_id'], ['project_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=True),
    sa.Column('custom_section_type', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('section_type_id', sa.Integer(), nullable=True),
    sa.Column('user_project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_type_id'], ['section_types.id'], ),
    sa.ForeignKeyConstraint(['user_project_id'], ['user_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flag', sa.Boolean(), nullable=True),
    sa.Column('item', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('project_section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_section_id'], ['project_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_items')
    op.drop_table('project_sections')
    op.drop_table('user_projects')
    op.drop_table('users')
    op.drop_table('section_types')
    op.drop_table('project_types')
    op.drop_table('domains')
    # ### end Alembic commands ###
