"""remove manager stuff from user db

Revision ID: 17b750ba1911
Revises: 6f7e96a76586
Create Date: 2024-11-13 05:59:49.887752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b750ba1911'
down_revision = '6f7e96a76586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('useDefaultManager')
        batch_op.drop_column('defaultManagerName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defaultManagerName', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('useDefaultManager', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
