"""add user settings

Revision ID: 6f7e96a76586
Revises: 97d437be57dd
Create Date: 2024-11-13 04:34:21.662888

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6f7e96a76586"
down_revision = "97d437be57dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tooltips", sa.Boolean(), nullable=False))
        batch_op.add_column(
            sa.Column("useDefaultManager", sa.Boolean(), nullable=False)
        )
        batch_op.add_column(sa.Column("completeProgress", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("highContrast", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("rowHeightPreset", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("rowExpandedPreset", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("defaultProjectType", sa.Integer(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("defaultProjectTheme", sa.Integer(), nullable=False)
        )
        batch_op.add_column(sa.Column("tooltipDelay", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("defaultManagerName", sa.String(length=25), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("defaultManagerName")
        batch_op.drop_column("tooltipDelay")
        batch_op.drop_column("defaultProjectTheme")
        batch_op.drop_column("defaultProjectType")
        batch_op.drop_column("rowExpandedPreset")
        batch_op.drop_column("rowHeightPreset")
        batch_op.drop_column("highContrast")
        batch_op.drop_column("completeProgress")
        batch_op.drop_column("useDefaultManager")
        batch_op.drop_column("tooltips")

    # ### end Alembic commands ###
