name: Deploy to Prouction

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PW }}
          script: |
            cd pambas/
            git fetch origin main
            git reset --hard origin/main
            docker-compose -f docker-compose.base.yml -f docker-compose.prod.yml stop
            docker-compose -f docker-compose.base.yml -f docker-compose.prod.yml down --rmi local --remove-orphans
            docker-compose -f docker-compose.base.yml -f docker-compose.prod.yml up -d --build --force-recreate
            docker image prune -f --filter "dangling=true"
